### Instruction
#### How to Run:
* Click the code-block you wnat to run to focus on it, press "ctr+enter" ro run code in that block;
* Press any key to skip to next experiment.

#### Processing & "Conclusions":
* **Try to run SIFT and its modifications on different scaled parts of video frames(.jpg);**
* **Turns out that maybe we do not need to use "slide-window" or "image-pyramid" techniques;**
* **McDonald's icon is extreamly hard to detect with SIFT methods.**

#### Next:
* Run SIFT with BFmatcher to detect brand icons in video frames and video;
* Focus on speed, accuracy and parameters.

### SIFT: BFmatcher

In [5]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

image_set = [
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_scaled.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_window.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_1.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_2.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_scaled.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_window.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_scaled.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_window.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_scaled.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_1.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_2.jpg'],
    
    [r'.\data\nfl_logo.jpg',
     r'.\data\subway_snapshoot_1_scaled.jpg']
]

for pick in range(1, len(image_set)+1):
    imgname1 = image_set[pick-1][0]
    imgname2 = image_set[pick-1][1]

    sift = cv2.xfeatures2d.SIFT_create()

    img1 = cv2.imread(imgname1)
    print(type(img1), img1.shape, img1[0])
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY) #灰度处理图像
    kp1, des1 = sift.detectAndCompute(img1,None)   #des是描述子

    img2 = cv2.imread(imgname2)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)#灰度处理图像
    kp2, des2 = sift.detectAndCompute(img2,None)  #des是描述子

    hmerge = np.hstack((gray1, gray2)) #水平拼接
    cv2.imshow("gray", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)

    img3 = cv2.drawKeypoints(img1,kp1,img1,color=(255,0,255)) #画出特征点，并显示为红色圆圈
    img4 = cv2.drawKeypoints(img2,kp2,img2,color=(255,0,255)) #画出特征点，并显示为红色圆圈
    hmerge = np.hstack((img3, img4)) #水平拼接
    cv2.imshow("point", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)
    # BFMatcher解决匹配
    bf = cv2.BFMatcher()
    matches = bf.knnMatch(des1,des2, k=2)
    # 调整ratio
    good = []
    for m,n in matches:
        if m.distance < 0.75*n.distance:
            good.append([m])

    ## img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,matches,None,flags=2)
    img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,good,None,flags=2)
    cv2.imshow("BFmatch", img5)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


<class 'numpy.ndarray'> (270, 480, 3) [[61 84  0]
 [61 84  0]
 [61 84  0]
 ...
 [61 84  0]
 [61 84  0]
 [61 84  0]]
<class 'numpy.ndarray'> (270, 480, 3) [[61 84  0]
 [61 84  0]
 [61 84  0]
 ...
 [61 84  0]
 [61 84  0]
 [61 84  0]]
<class 'numpy.ndarray'> (270, 480, 3) [[61 84  0]
 [61 84  0]
 [61 84  0]
 ...
 [61 84  0]
 [61 84  0]
 [61 84  0]]
<class 'numpy.ndarray'> (270, 480, 3) [[61 84  0]
 [61 84  0]
 [61 84  0]
 ...
 [61 84  0]
 [61 84  0]
 [61 84  0]]
<class 'numpy.ndarray'> (270, 480, 3) [[104  51   1]
 [104  51   1]
 [104  51   1]
 ...
 [104  51   1]
 [104  51   1]
 [104  51   1]]
<class 'numpy.ndarray'> (270, 480, 3) [[104  51   1]
 [104  51   1]
 [104  51   1]
 ...
 [104  51   1]
 [104  51   1]
 [104  51   1]]
<class 'numpy.ndarray'> (270, 480, 3) [[ 66 112   0]
 [ 66 112   0]
 [ 66 112   0]
 ...
 [ 66 112   0]
 [ 66 112   0]
 [ 66 112   0]]
<class 'numpy.ndarray'> (270, 480, 3) [[ 66 112   0]
 [ 66 112   0]
 [ 66 112   0]
 ...
 [ 66 112   0]
 [ 66 112   0]
 [ 66 112   0]]


### SIFT: FlannBasedMatcher

In [8]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

image_set = [
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_scaled.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_window.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_1.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_2.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_scaled.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_window.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_scaled.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_window.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_scaled.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_1.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_2.jpg']
]

for pick in range(1, len(image_set)+1):
    imgname1 = image_set[pick-1][0]
    imgname2 = image_set[pick-1][1]

    sift = cv2.xfeatures2d.SIFT_create()

    # FLANN 参数设计
    FLANN_INDEX_KDTREE = 0
    index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
    search_params = dict(checks=50)
    flann = cv2.FlannBasedMatcher(index_params,search_params)

    img1 = cv2.imread(imgname1)
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY) #灰度处理图像
    kp1, des1 = sift.detectAndCompute(img1,None)#des是描述子

    img2 = cv2.imread(imgname2)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    kp2, des2 = sift.detectAndCompute(img2,None)

    hmerge = np.hstack((gray1, gray2)) #水平拼接
    cv2.imshow("gray", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)

    img3 = cv2.drawKeypoints(img1,kp1,img1,color=(255,0,255))
    img4 = cv2.drawKeypoints(img2,kp2,img2,color=(255,0,255))

    hmerge = np.hstack((img3, img4)) #水平拼接
    cv2.imshow("point", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)
    matches = flann.knnMatch(des1,des2,k=2)
    matchesMask = [[0,0] for i in range(len(matches))]

    good = []
    for m,n in matches:
        if m.distance < 0.7*n.distance:
            good.append([m])

    ## img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,matches,None,flags=2)
    img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,good,None,flags=2)
    cv2.imshow("FLANN", img5)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


### SURF: FlannBasedMatcher

In [1]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

image_set = [
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_scaled.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_window.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_1.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_2.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_scaled.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_window.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_scaled.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_window.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_scaled.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_1.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_2.jpg']
]

for pick in range(1, len(image_set)+1):
    imgname1 = image_set[pick-1][0]
    imgname2 = image_set[pick-1][1]

    surf = cv2.xfeatures2d.SURF_create()

    FLANN_INDEX_KDTREE = 0
    index_params = dict(algorithm = FLANN_INDEX_KDTREE, trees = 5)
    search_params = dict(checks=50)
    flann = cv2.FlannBasedMatcher(index_params,search_params)

    img1 = cv2.imread(imgname1)
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY) #灰度处理图像
    kp1, des1 = surf.detectAndCompute(img1,None)#des是描述子

    img2 = cv2.imread(imgname2)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    kp2, des2 = surf.detectAndCompute(img2,None)

    hmerge = np.hstack((gray1, gray2)) #水平拼接
    cv2.imshow("gray", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)

    img3 = cv2.drawKeypoints(img1,kp1,img1,color=(255,0,255))
    img4 = cv2.drawKeypoints(img2,kp2,img2,color=(255,0,255))

    hmerge = np.hstack((img3, img4)) #水平拼接
    cv2.imshow("point", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)

    matches = flann.knnMatch(des1,des2,k=2)

    good = []
    for m,n in matches:
        if m.distance < 0.7*n.distance:
            good.append([m])

    ## img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,matches,None,flags=2)
    img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,good,None,flags=2)
    cv2.imshow("SURF", img5)
    cv2.waitKey(0)
    cv2.destroyAllWindows()


### ORB: BFMatcher

In [2]:
import numpy as np
import cv2
from matplotlib import pyplot as plt

image_set = [
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_scaled.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_2_window.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_1.jpg'],
    
    [r'.\data\subway_logo.jpg',
     r'.\data\subway_snapshoot_1_window_2.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_scaled.jpg'],
    
    [r'.\data\nfl_logo.jpg', 
     r'.\data\nfl_snapshoot_window.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_scaled.jpg'],
    
    [r'.\data\starbucks_logo.jpg',
     r'.\data\starbucks_snapshoot_window.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_scaled.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_1.jpg'],
    
    [r'.\data\mcdonalds_logo.jpg',
     r'.\data\mc_snapshoot_window_2.jpg']
]

for pick in range(1, len(image_set)+1):
    imgname1 = image_set[pick-1][0]
    imgname2 = image_set[pick-1][1]

    orb = cv2.ORB_create()

    img1 = cv2.imread(imgname1)
    gray1 = cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY) #灰度处理图像
    kp1, des1 = orb.detectAndCompute(img1,None)#des是描述子

    img2 = cv2.imread(imgname2)
    gray2 = cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)
    kp2, des2 = orb.detectAndCompute(img2,None)

    hmerge = np.hstack((gray1, gray2)) #水平拼接
    cv2.imshow("gray", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)

    img3 = cv2.drawKeypoints(img1,kp1,img1,color=(255,0,255))
    img4 = cv2.drawKeypoints(img2,kp2,img2,color=(255,0,255))

    hmerge = np.hstack((img3, img4)) #水平拼接
    cv2.imshow("point", hmerge) #拼接显示为gray
    ## cv2.waitKey(0)

    # BFMatcher解决匹配
    bf = cv2.BFMatcher()
    matches = bf.knnMatch(des1,des2, k=2)

    # 调整ratio
    good = []
    for m,n in matches:
        if m.distance < 0.75*n.distance:
            good.append([m])

    ## img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,matches,None,flags=2)
    img5 = cv2.drawMatchesKnn(img1,kp1,img2,kp2,good,None,flags=2)
    cv2.imshow("ORB", img5)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
